version: '3.8'
services:
  tomcat:
    image: tomcat:10-jdk17-openjdk
    ports:
      - "8080:8080"
    volumes:
      - ./target/help-service-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/help-service.war
    restart: on-failure